# Generated by Django 5.0 on 2023-12-13 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='relationship',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='work',
            field=models.TextField(blank=True),
        ),
    ]
